# Generated by Django 3.2 on 2021-04-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('type', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('completion_rate', models.IntegerField(blank=True, default=False, null=True)),
                ('open_rate', models.IntegerField(blank=True, default=False, null=True)),
                ('is_default', models.IntegerField(blank=True, default=False, null=True)),
                ('is_default_form_of_default_survey', models.IntegerField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(blank=True, default=False, null=True)),
                ('question_label', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('question_type', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_id', models.IntegerField(blank=True, default=False, null=True)),
                ('is_conditional_question', models.BooleanField(blank=True, default=False, null=True)),
                ('is_required', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, default=False, max_length=10, null=True)),
                ('min_range', models.IntegerField(blank=True, default=False, null=True)),
                ('max_range', models.IntegerField(blank=True, default=False, null=True)),
                ('form_key', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.form')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('form_id', models.IntegerField(blank=True, default=False, null=True)),
                ('form_type', models.IntegerField(blank=True, default=False, null=True)),
                ('last_opened_at', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('last_opened_from_browser', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('last_opened_from_location', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('last_opened_from_location_city', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('last_opened_from_location_region', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('last_opened_from_location_country', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('is_form_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('form_completed_at', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('last_touched_question_id', models.IntegerField(blank=True, default=False, null=True)),
                ('form_key', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.form')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('type', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('form_key', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.form')),
            ],
        ),
    ]
