# Generated by Django 3.2 on 2021-04-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='form_key',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.form'),
        ),
    ]
