# Generated by Django 3.2 on 2021-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0002_alter_question_form_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('field_2', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('field_3', models.CharField(blank=True, default=False, max_length=50, null=True)),
            ],
        ),
    ]
