# Generated by Django 3.2 on 2021-04-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='form_key',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.form'),
        ),
        migrations.AlterField(
            model_name='activitystream',
            name='form_key',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.form'),
        ),
    ]
