# Generated by Django 3.2 on 2021-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0005_alter_activitystream_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystream',
            name='last_opened_from_browser',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitystream',
            name='last_opened_from_location',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitystream',
            name='last_opened_from_location_city',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
