# Generated by Django 3.2 on 2021-04-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0006_auto_20210412_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='account_name',
        ),
        migrations.AddField(
            model_name='account',
            name='account_password',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
