# Generated by Django 3.2 on 2021-04-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0007_auto_20210413_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(blank=True, default=False, null=True)),
                ('shop_id', models.IntegerField(blank=True, default=False, null=True)),
                ('order_id', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('product_id', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('review_hash', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('review_status', models.CharField(blank=True, default=False, max_length=50, null=True)),
                ('is_published', models.BooleanField(blank=True, null=True)),
                ('published_at', models.BooleanField(blank=True, null=True)),
                ('is_withdrawn', models.IntegerField(blank=True, default=False, null=True)),
                ('withdrawn_at', models.IntegerField(blank=True, default=False, null=True)),
                ('result_forms_id', models.IntegerField(blank=True, default=False, null=True)),
                ('results_form_default_language', models.IntegerField(blank=True, default=False, null=True)),
                ('results_ip_address', models.IntegerField(blank=True, default=False, null=True)),
                ('results_forms_cloned_from', models.IntegerField(blank=True, default=False, null=True)),
                ('results_forms_submitted_at', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_no_answer', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_question_tags', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_cloned_from', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_answer_value', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_answer_value_option_option_id', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_answer_value_option_option_label', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_answer_value_option_linked_questions', models.IntegerField(blank=True, default=False, null=True)),
                ('results_questions_mapped_value', models.IntegerField(blank=True, default=False, null=True)),
                ('question_key', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.question')),
            ],
        ),
    ]
