# Generated by Django 3.2 on 2021-04-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0008_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_key',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_importer.question'),
        ),
    ]
