# Generated by Django 3.2 on 2021-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0009_alter_answer_question_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='results_questions_field_to_submit_on_ekomi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value_option_linked_questions',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value_option_option_id',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value_option_option_label',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
