# Generated by Django 3.2 on 2021-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_importer', '0015_alter_answer_results_questions_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='order_id',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='product_id',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_form_default_language',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_ip_address',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value_option_linked_questions',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value_option_option_id',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_answer_value_option_option_label',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results_questions_question_tags',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='review_hash',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='review_status',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
